server:
  port: 8081

dubbo:
  application:
    id: provider
    name: provider
  registry:
    address: zookeeper://192.168.1.114:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.wyl.dubbo.service.impl