server:
  port: 8081

security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
      scope: app
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

