spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-umi?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.wyl.springbootmybatis.model
  mapper-locations: mapper/**.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql